[pytest]
addopts = -v -s --html=reports/relatorio.html --self-contained-html
markers =
    smoke: Testes rápidos de disponibilidade
    contract: Validações de estrutura e tipos de dados
    performance: Testes de SLA e tempo de resposta
    error: Validação de tratamento de falhas
log_cli = true
log_cli_level = INFO